### ISSUE TITLE
Automatically pad barcodes shorter than 14 digits with leading zeros

### ISSUE THREAD

**Issue by ENT8R** [ferrisoxide/brocade.io#27]
I think that it would make sense to add leading zeros to the barcode if it is shorter than 14 digits. Otherwise searching for the more common variants of EAN-8, EAN-13 or the GTIN counterparts doesn't lead to a result...
As far as I remember this was also the default behavior of datakick's API.

e.g. the following doesn't work as expected, as it's a EAN-13 barcode:
https://www.brocade.io/api/items/4012200328002
but padded with a leading zero to form a EAN-14 the correct item is returned:
https://www.brocade.io/api/items/04012200328002

If you don't think that this addition makes sense in this repository, I can as well change it in my downstream library 😄

**Comment by ENT8R** [comment]
And maybe even do some validation of the resulting input barcode? As sometimes a user might supply a wrong or badly formatted barcode...

**Comment by ferrisoxide** [comment]
Hi @ENT8R 

This makes sense. I'll add padding / validation when I get back to working on Brocade, probably early next week.

Thanks for the input - it's appreciated.

**Comment by ENT8R** [comment]
Sounds great! Thank you for your work. Yesterday I converted the node.js library from using the old datakick API to the new Brocade API and already released it on npm (https://www.npmjs.com/package/node-brocade). The simple package name "brocade" is sadly already in use which is why I had to use the "node-" prefix...

**Comment by ferrisoxide** [comment]
@ENT8R 

OK, I may have mucked this app. First cut was just to make sure that the following both return a record:

https://www.brocade.io/api/items/4012200328002
https://www.brocade.io/api/items/04012200328002

Basically, it's now regex'ing and matching whether leading zeroes are used in the query or not. Internally it's still recording barcodes as explicitly EAN-13 or EAN-14, and I have yet to make a call whether or not to just standardise on EAN-14.

Does this meet your needs, or is there a better way?

**Comment by ENT8R** [comment]
Yes, this looks good! Thank you for your quick response 👍
