### ISSUE TITLE
Search - Error when no results found

### ISSUE THREAD

**Issue by MrRedBeard** [ferrisoxide/brocade.io#35]
Occasionally a search returns a server side error when results are not found or times out. Seems to happen mainly when a new search is submitted. 

**Query**
https://www.brocade.io/api/items?query=peanux

![Error](https://user-images.githubusercontent.com/10256850/85092878-52384000-b1b0-11ea-9418-f9936b846fae.PNG)

**Comment by MrRedBeard** [comment]
This happens whenever I search with more than one word or if the search includes '&'

**Comment by ferrisoxide** [comment]
It looks like the introduction of searching for gtin-13/14 via regex that has done this. It was overly "clever" to do this using regex, so I'll swap to a more basic approach and see if that helps.

**Comment by ferrisoxide** [comment]
@MrRedBeard This should be fixed now. My apologies

**Comment by MrRedBeard** [comment]
Awesome thanks! Special characters in search like "&" still cause it to error out. If you would like I can submit a new issue for this one?

![Error2](https://user-images.githubusercontent.com/10256850/85723579-fe01f400-b6b8-11ea-93e5-c4b886dafb94.PNG)

**Comment by ferrisoxide** [comment]
@MrRedBeard The issue with `&` and other non-alphanumeric chars should be sorted now.

**Comment by ferrisoxide** [comment]
Checked on production. Closing.
