### ISSUE TITLE
No emails can be send

### ISSUE THREAD

**Issue by Syndesi** [ferrisoxide/brocade.io#67]
Hi,

emails can not be send, I get repeatably the following error:
![Screenshot 2022-01-08 at 14-20-28 We're sorry, but something went wrong (500)](https://user-images.githubusercontent.com/9903723/148645737-861951d3-6d64-465f-8d73-ea6a8cbbf07b.png)
Due to this email addresses can not be verificated and new users, e.g. me, can not sign up.

Regards,
Syndesi

**Comment by ferrisoxide** [comment]
Apologies for the delay @Syndesi - I'll look into this _post haste_

**Comment by ferrisoxide** [comment]
OK, it looks like the provider we were using (Mailjet) is no longer available on Heroku. There are other providers - I'll just need to set aside some time to review what provider is going to serve our needs going forward.

Again, apologies for the delay.

**Comment by ferrisoxide** [comment]
@Syndesi The problem with emails has been resolved. Again, apologies for the delay. I'm trying to set aside more time to work on brocade, but life can get in the way.

Please let me know if you still have issues signing in, etc.

**Comment by Syndesi** [comment]
@ferrisoxide thank you very much, I can confirm that it now works :D
Just a small heads up: After I clicked on the confirmation link, I was redirected to the unencrypted version of the site (`http://www.brocade.io/...`).
Isn't really a problem, though https would be nice.
Thanks for the dedicated support :D

**Comment by ferrisoxide** [comment]
@Syndesi 

> Isn't really a problem, though https would be nice.

Thanks heaps for the feedback. This should be sorted now.

**Comment by Syndesi** [comment]
@ferrisoxide thanks, https works now :D
